[package]
name = "science"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
approx = "0.5.1"
nalgebra = { version = "0.33.0", features = ["serde-serialize"] }
ndarray = "0.16.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
