[package]
name = "encoding"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
byteorder = "1.5.0"
csv = "1.3.0"
data-encoding = "2.6.0"
percent-encoding = "2.3.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
toml = "0.8.19"
url = "2.5.2"
