name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: |
          cargo test -p algorithms --verbose -- --show-output
          cargo test -p command_line --verbose -- --show-output
          cargo test -p cryptography --verbose -- --show-output
          cargo test -p data_structures --verbose -- --show-output
          cargo test -p database --verbose -- --show-output
          cargo test -p date_time --verbose -- --show-output
          cargo test -p development_tools --verbose -- --show-output
          cargo test -p encoding --verbose -- --show-output
          cargo test -p error_handling --verbose -- --show-output
          cargo test -p file_system --verbose -- --show-output
          cargo test -p hardware_support --verbose -- --show-output
          cargo test -p shared --verbose -- --show-output
          cargo test -p threads --verbose -- --show-output
